# Generated by Django 6.0.2 on 2026-03-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_orderitem_price_at_purchase_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_purchase',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
