# Generated by Django 6.0.2 on 2026-05-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='shiping_adress_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
