# Generated by Django 6.0.2 on 2026-05-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_billing_address_snapshot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shiping_adress_snapshot',
            new_name='shipping_address_snapshot',
        ),
    ]
